name: Update Tags

on:
  push:
    tags:
      - v*.*.*

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse semver
        uses: madhead/semver-utils@v2
        id: version
        with:
          version: ${{ github.ref_name }}

      - name: Update tags
        run: |
          TAGS='v${{ steps.version.outputs.major }} v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}'
          for t in $TAGS; do
            git tag -f "$t"
            git push -f origin "refs/tags/$t"
          done
